-- =================================================================
-- PostgreSQL 数据库初始化脚本 (优化版)
-- 模块：用户与角色核心管理
-- 版本：2.0.3-Fixed
-- 说明：修复了主键缺失、Owner 硬编码、扩展依赖及幂等性问题，调整了UUID字段命名
-- =================================================================

-- 0. 先回滚任何已失败的事务，确保干净的开始
ROLLBACK;

-- 1. 开启事务，确保原子性
BEGIN;

-- 2. 设置环境参数
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

-- 3. 确保 UUID 扩展存在 (gen_random_uuid() 需要 pgcrypto)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =================================================================
-- 清理旧对象 (支持重复执行脚本)
-- 注意：生产环境请谨慎使用 DROP CASCADE，它会删除依赖此表的外键
-- =================================================================
DROP TABLE IF EXISTS public.sys_user_roles CASCADE;
DROP TABLE IF EXISTS public.sys_user CASCADE;
DROP TABLE IF EXISTS public.sys_role CASCADE;
DROP TABLE IF EXISTS public.app CASCADE;
DROP FUNCTION IF EXISTS public.update_updated_time() CASCADE;

-- =================================================================
-- 创建公共函数：自动更新 updated_time
-- =================================================================
CREATE OR REPLACE FUNCTION public.update_updated_time()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_time = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =================================================================
-- 1. 创建角色表 (sys_role)
-- =================================================================
CREATE TABLE public.sys_role (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(40) NOT NULL,
    code character varying(20),
    "order" integer NOT NULL DEFAULT 0,
    data_scope integer NOT NULL DEFAULT 1,
    uuid character varying(64) NOT NULL DEFAULT gen_random_uuid()::text,
    status character varying(10) NOT NULL DEFAULT '0',
    description text,
    created_time timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_time timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_sys_role PRIMARY KEY (id)
);

COMMENT ON TABLE public.sys_role IS '角色表';
COMMENT ON COLUMN public.sys_role.id IS '主键ID';
COMMENT ON COLUMN public.sys_role.name IS '角色名称';
COMMENT ON COLUMN public.sys_role.code IS '角色编码';
COMMENT ON COLUMN public.sys_role."order" IS '显示排序';
COMMENT ON COLUMN public.sys_role.data_scope IS '数据权限范围(1:仅本人 2:本部门 3:本部门及以下 4:全部 5:自定义)';
COMMENT ON COLUMN public.sys_role.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN public.sys_role.status IS '是否启用(0:启用 1:禁用)';
COMMENT ON COLUMN public.sys_role.description IS '备注/描述';
COMMENT ON COLUMN public.sys_role.created_time IS '创建时间';
COMMENT ON COLUMN public.sys_role.updated_time IS '更新时间';

-- =================================================================
-- 2. 创建用户表 (sys_user)
-- =================================================================
CREATE TABLE public.sys_user (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(32) NOT NULL,
    password character varying(255) NOT NULL,
    name character varying(32) NOT NULL,
    uuid character varying(64) NOT NULL DEFAULT gen_random_uuid()::text,
    mobile character varying(20), -- 放宽长度以支持国际号码
    email character varying(64),
    gender character varying(1) DEFAULT '2',
    avatar character varying(255),
    is_superuser boolean NOT NULL DEFAULT false,
    last_login timestamp with time zone,
    gitee_login character varying(32),
    github_login character varying(32),
    wx_login character varying(32),
    qq_login character varying(32),
    dept_id integer,
    status character varying(10) NOT NULL DEFAULT '0',
    description text,
    created_time timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_time timestamp without time zone NOT NULL DEFAULT NOW(),
    created_id integer,
    updated_id integer,
    CONSTRAINT pk_sys_user PRIMARY KEY (id),
    CONSTRAINT uk_sys_user_uuid UNIQUE (uuid)
);

COMMENT ON TABLE public.sys_user IS '用户表';
COMMENT ON COLUMN public.sys_user.id IS '主键ID';
COMMENT ON COLUMN public.sys_user.username IS '用户名/登录账号';
COMMENT ON COLUMN public.sys_user.password IS '密码哈希';
COMMENT ON COLUMN public.sys_user.name IS '昵称';
COMMENT ON COLUMN public.sys_user.uuid IS '用户UUID全局唯一标识';
COMMENT ON COLUMN public.sys_user.mobile IS '手机号';
COMMENT ON COLUMN public.sys_user.email IS '邮箱';
COMMENT ON COLUMN public.sys_user.gender IS '性别(0:男 1:女 2:未知)';
COMMENT ON COLUMN public.sys_user.avatar IS '头像URL地址';
COMMENT ON COLUMN public.sys_user.is_superuser IS '是否超管';
COMMENT ON COLUMN public.sys_user.last_login IS '最后一次登录时间';
COMMENT ON COLUMN public.sys_user.gitee_login IS 'Gitee登录';
COMMENT ON COLUMN public.sys_user.github_login IS 'Github登录';
COMMENT ON COLUMN public.sys_user.wx_login IS '微信登录';
COMMENT ON COLUMN public.sys_user.qq_login IS 'QQ登录';
COMMENT ON COLUMN public.sys_user.dept_id IS '部门ID';
COMMENT ON COLUMN public.sys_user.status IS '是否启用(0:启用 1:禁用)';
COMMENT ON COLUMN public.sys_user.description IS '备注/描述';
COMMENT ON COLUMN public.sys_user.created_time IS '创建时间';
COMMENT ON COLUMN public.sys_user.updated_time IS '更新时间';
COMMENT ON COLUMN public.sys_user.created_id IS '创建人ID';
COMMENT ON COLUMN public.sys_user.updated_id IS '更新人ID';

-- =================================================================
-- 3. 创建用户角色关联表 (sys_user_roles)
-- =================================================================
CREATE TABLE public.sys_user_roles (
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT pk_sys_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_sys_user_roles_user FOREIGN KEY (user_id) REFERENCES public.sys_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_sys_user_roles_role FOREIGN KEY (role_id) REFERENCES public.sys_role(id) ON DELETE CASCADE
);

COMMENT ON TABLE public.sys_user_roles IS '用户角色关联表';
COMMENT ON COLUMN public.sys_user_roles.user_id IS '用户ID';
COMMENT ON COLUMN public.sys_user_roles.role_id IS '角色ID';

-- =================================================================
-- 4. 创建索引
-- =================================================================
CREATE INDEX idx_sys_user_username ON public.sys_user USING btree (username);
CREATE INDEX idx_sys_user_mobile ON public.sys_user USING btree (mobile);
CREATE INDEX idx_sys_user_email ON public.sys_user USING btree (email);
CREATE INDEX idx_sys_user_status ON public.sys_user USING btree (status);
CREATE INDEX idx_sys_role_code ON public.sys_role USING btree (code);

-- =================================================================
-- 5. 创建触发器 (自动更新 updated_time)
-- =================================================================
CREATE TRIGGER update_sys_user_updated_time
BEFORE UPDATE ON public.sys_user
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_time();

CREATE TRIGGER update_sys_role_updated_time
BEFORE UPDATE ON public.sys_role
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_time();

-- =================================================================
-- 6. 插入初始数据
-- =================================================================

-- 6.1 插入默认超级管理员
-- 用户名: admin
-- 密码: admin123 (BCrypt 哈希: $argon2id$v=19$m=65536,t=3,p=4$vXchZ5IJb5m0iSsw+lB2MA$MzdSo0ikqcKMpubW6HMrmZgRjnPdBHd3ssVADb6tVoY)
INSERT INTO public.sys_user (
    username, password, name, is_superuser, status, description,mobile
) VALUES (
    'admin',
    '$argon2id$v=19$m=65536,t=3,p=4$vXchZ5IJb5m0iSsw+lB2MA$MzdSo0ikqcKMpubW6HMrmZgRjnPdBHd3ssVADb6tVoY',
    '超级管理员',
    true,
    '0',
    '系统内置最高权限账号',
    '18770335001'
);

-- 6.2 插入默认角色
INSERT INTO public.sys_role (
    name, code, "order", data_scope, status, description
) VALUES (
    '超级管理员',
    'admin',
    1,
    4,
    '0',
    '拥有系统所有权限及数据访问权'
);

-- 6.3 关联管理员与角色
-- 注意：由于使用了 IDENTITY 列，ID 从 1 开始自增，这里假设插入顺序保证 ID 为 1
INSERT INTO public.sys_user_roles (user_id, role_id)
VALUES (1, 1);

-- =================================================================
-- 创建 AI应用表 (app)
-- 用途：存储用户创建的AI应用/工作流基本信息和权限控制
-- 完整工作流配置存储在 MongoDB apps 集合中
-- =================================================================
CREATE TABLE public.app (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(200) NOT NULL,
    uuid character varying(64) NOT NULL DEFAULT gen_random_uuid()::text,
    user_id integer NOT NULL,
    description text,
    icon character varying(20) DEFAULT '🤖',
    is_public boolean NOT NULL DEFAULT false,
    type character varying(20) NOT NULL DEFAULT 'workflow',
    status character varying(10) NOT NULL DEFAULT '0',
    is_deleted boolean NOT NULL DEFAULT false,
    created_time timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_time timestamp without time zone NOT NULL DEFAULT NOW(),
    created_id integer,
    updated_id integer,
    CONSTRAINT pk_app PRIMARY KEY (id),
    CONSTRAINT uk_app_uuid UNIQUE (uuid)
);

COMMENT ON TABLE public.app IS 'AI应用表 - 存储应用基本信息和权限';
COMMENT ON COLUMN public.app.id IS '主键ID';
COMMENT ON COLUMN public.app.name IS '应用名称';
COMMENT ON COLUMN public.app.uuid IS '应用唯一标识，对应MongoDB App.uuid';
COMMENT ON COLUMN public.app.user_id IS '创建用户ID (权限控制)';
COMMENT ON COLUMN public.app.description IS '应用描述';
COMMENT ON COLUMN public.app.icon IS '应用图标emoji';
COMMENT ON COLUMN public.app.is_public IS '是否公开分享';
COMMENT ON COLUMN public.app.type IS '应用类型: workflow/ai/chat';
COMMENT ON COLUMN public.app.status IS '是否启用(0:启用 1:禁用)';
COMMENT ON COLUMN public.app.is_deleted IS '是否软删除';
COMMENT ON COLUMN public.app.created_time IS '创建时间';
COMMENT ON COLUMN public.app.updated_time IS '更新时间';
COMMENT ON COLUMN public.app.created_id IS '创建人ID';
COMMENT ON COLUMN public.app.updated_id IS '更新人ID';

-- 创建索引
CREATE INDEX idx_app_user_id ON public.app USING btree (user_id);
CREATE INDEX idx_app_status ON public.app USING btree (status);
CREATE INDEX idx_app_type ON public.app USING btree (type);
CREATE INDEX idx_app_is_public ON public.app USING btree (is_public);
CREATE INDEX idx_app_created_id ON public.app USING btree (created_id);
CREATE INDEX idx_app_updated_id ON public.app USING btree (updated_id);

-- 创建触发器 (自动更新 updated_time)
CREATE TRIGGER update_app_updated_time
BEFORE UPDATE ON public.app
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_time();

-- =================================================================
-- 插入默认应用
-- =================================================================
-- 1. 示例工作流应用（对应 MongoDB default-apps.json 第一个文档）
INSERT INTO public.app (
    uuid, name, description, icon, is_public, type, user_id
) VALUES (
    '8488bff8-30a2-415d-8d1d-7c4fb4b6567b',
    '示例工作流',
    '这是一个示例条件分支工作流，展示多分支路由能力',
    '🌐',
    true,
    'WORKFLOW',
    1
);

-- 2. 默认聊天助手（对应 MongoDB default-apps.json 第二个文档）
INSERT INTO public.app (
    uuid, name, description, icon, is_public, type, user_id
) VALUES (
    '9a8aa9f8-41b2-52cd-9e2a-8d5ea12c4d3e',
    '默认聊天助手',
    '一个通用的AI对话助手',
    '🤖',
    true,
    'CHAT',
    1
);

-- =================================================================
-- 创建知识库表 (knowledge_base)
-- 用途：存储向量知识库元数据，每个知识库对应一张独立的向量表 kb_{id}_embedding
-- =================================================================
DROP TABLE IF EXISTS public.knowledge_base CASCADE;
CREATE TABLE public.knowledge_base (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    uuid character varying(64) NOT NULL DEFAULT gen_random_uuid()::text,
    name character varying(256) NOT NULL,
    collection_name character varying(128) NOT NULL,
    status character varying(10) NOT NULL DEFAULT '0',
    description text,
    embedding_model character varying(64) NOT NULL DEFAULT 'text-embedding-v4',
    search_model character varying(64) NOT NULL DEFAULT 'qwen-max',
    text_process_model character varying(64),
    image_understand_model character varying(64),
    dimension integer NOT NULL DEFAULT 1536,
    is_deleted boolean NOT NULL DEFAULT false,
    created_time timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_time timestamp without time zone NOT NULL DEFAULT NOW(),
    created_id integer,
    updated_id integer,
    CONSTRAINT pk_knowledge_base PRIMARY KEY (id),
    CONSTRAINT uk_knowledge_base_uuid UNIQUE (uuid),
    CONSTRAINT uk_knowledge_base_collection UNIQUE (collection_name)
);

COMMENT ON TABLE public.knowledge_base IS '知识库表 - 存储向量知识库元数据';
COMMENT ON COLUMN public.knowledge_base.id IS '主键ID';
COMMENT ON COLUMN public.knowledge_base.uuid IS '知识库UUID全局唯一标识';
COMMENT ON COLUMN public.knowledge_base.name IS '知识库名称';
COMMENT ON COLUMN public.knowledge_base.collection_name IS 'PGVector向量表名，格式: kb_{id}_embedding';
COMMENT ON COLUMN public.knowledge_base.status IS '状态: 0-正常 1-禁用';
COMMENT ON COLUMN public.knowledge_base.description IS '知识库描述';
COMMENT ON COLUMN public.knowledge_base.embedding_model IS '使用的嵌入模型名称';
COMMENT ON COLUMN public.knowledge_base.search_model IS '搜索后回答LLM模型';
COMMENT ON COLUMN public.knowledge_base.text_process_model IS '文本预处理/问答提取模型';
COMMENT ON COLUMN public.knowledge_base.image_understand_model IS '图片理解模型';
COMMENT ON COLUMN public.knowledge_base.dimension IS '向量维度';
COMMENT ON COLUMN public.knowledge_base.is_deleted IS '是否软删除';
COMMENT ON COLUMN public.knowledge_base.created_time IS '创建时间';
COMMENT ON COLUMN public.knowledge_base.updated_time IS '更新时间';
COMMENT ON COLUMN public.knowledge_base.created_id IS '创建人ID';
COMMENT ON COLUMN public.knowledge_base.updated_id IS '更新人ID';

-- 创建索引
CREATE INDEX idx_knowledge_base_created_id ON public.knowledge_base USING btree (created_id);
CREATE INDEX idx_knowledge_base_status ON public.knowledge_base USING btree (status);
CREATE INDEX idx_knowledge_base_is_deleted ON public.knowledge_base USING btree (is_deleted);

-- 创建触发器 (自动更新 updated_time)
CREATE TRIGGER update_knowledge_base_updated_time
BEFORE UPDATE ON public.knowledge_base
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_time();

-- =================================================================
-- 创建知识库文件表 (knowledge_file)
-- 用途：存储文件/文档元数据，不存content，content+向量存在 PGVector 中
-- =================================================================
-- 设计思路:
-- 一个用户上传的文件 → 切分为N个chunk → 每个chunk存入PGVector
-- KnowledgeFile 只存这个文件的**元信息**，方便管理和列表展示
-- =================================================================
DROP TABLE IF EXISTS public.knowledge_file CASCADE;
CREATE TABLE public.knowledge_file (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    uuid character varying(64) NOT NULL DEFAULT gen_random_uuid()::text,
    knowledge_base_id integer NOT NULL,
    file_name character varying(256) NOT NULL,
    description text,
    file_size bigint,
    chunk_count integer NOT NULL DEFAULT 0,
    source character varying(512),
    status integer NOT NULL DEFAULT 0,
    is_deleted boolean NOT NULL DEFAULT false,
    created_time timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_time timestamp without time zone NOT NULL DEFAULT NOW(),
    created_id integer,
    updated_id integer,
    CONSTRAINT pk_knowledge_file PRIMARY KEY (id),
    CONSTRAINT uk_knowledge_file_uuid UNIQUE (uuid)
);

COMMENT ON TABLE public.knowledge_file IS '知识库文件表 - 存储文件/文档元数据（content不在这里存储）';
COMMENT ON COLUMN public.knowledge_file.id IS '主键ID';
COMMENT ON COLUMN public.knowledge_file.uuid IS '文件UUID';
COMMENT ON COLUMN public.knowledge_file.knowledge_base_id IS '所属知识库ID';
COMMENT ON COLUMN public.knowledge_file.file_name IS '文件名/文档标题';
COMMENT ON COLUMN public.knowledge_file.description IS '文件描述';
COMMENT ON COLUMN public.knowledge_file.file_size IS '原始文件大小(字节)';
COMMENT ON COLUMN public.knowledge_file.chunk_count IS '切片数量';
COMMENT ON COLUMN public.knowledge_file.source IS '文档来源(文件路径/URL)';
COMMENT ON COLUMN public.knowledge_file.status IS '状态: 0-处理中 1-成功 2-失败';
COMMENT ON COLUMN public.knowledge_file.is_deleted IS '是否软删除';
COMMENT ON COLUMN public.knowledge_file.created_time IS '创建时间';
COMMENT ON COLUMN public.knowledge_file.updated_time IS '更新时间';
COMMENT ON COLUMN public.knowledge_file.created_id IS '创建人ID';
COMMENT ON COLUMN public.knowledge_file.updated_id IS '更新人ID';

-- 创建索引
CREATE INDEX idx_knowledge_file_knowledge_base_id ON public.knowledge_file USING btree (knowledge_base_id);
CREATE INDEX idx_knowledge_file_status ON public.knowledge_file USING btree (status);
CREATE INDEX idx_knowledge_file_is_deleted ON public.knowledge_file USING btree (is_deleted);

-- 创建触发器 (自动更新 updated_time)
CREATE TRIGGER update_knowledge_file_updated_time
BEFORE UPDATE ON public.knowledge_file
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_time();

-- =================================================================
-- 插入示例数据
-- =================================================================
-- 1. 示例知识库: 个人笔记 (id=1 → collection_name=kb_1_embedding)
INSERT INTO public.knowledge_base (
    name, collection_name, description, embedding_model, created_id
) VALUES (
    '个人学习笔记',
    'kb_1_embedding',
    '存储个人学习笔记和技术文档，用于AI问答',
    'text-embedding-v4',
    1
);

-- 2. 示例知识库: 项目文档 (id=2 → collection_name=kb_2_embedding)
INSERT INTO public.knowledge_base (
    name, collection_name, description, embedding_model, created_id
) VALUES (
    '项目开发文档',
    'kb_2_embedding',
    'SmartCustom 项目开发文档和API说明',
    'text-embedding-v4',
    1
);

-- 3. 示例文档 (个人笔记 - 第一条)
INSERT INTO public.knowledge_file (
    knowledge_base_id, file_name, chunk_count, source, status, created_id
) VALUES (
    1,
    'LangGraph 简介',
    1,
    'https://langchain-ai.github.io/langgraph/',
    1,
    1
);

-- 4. 示例文档 (个人笔记 - 第二条)
INSERT INTO public.knowledge_file (
    knowledge_base_id, file_name, chunk_count, source, status, created_id
) VALUES (
    1,
    'PGVector 使用说明',
    1,
    '项目笔记',
    1,
    1
);

-- 5. 示例文档 (项目文档)
INSERT INTO public.knowledge_file (
    knowledge_base_id, file_name, chunk_count, source, status, created_id
) VALUES (
    2,
    '项目架构说明',
    1,
    'README.md',
    1,
    1
);

-- =================================================================
-- 7. 提交事务
-- =================================================================
COMMIT;

-- 验证提示 (可选，执行完后可取消注释查看结果)
-- SELECT '初始化完成！当前用户数：' || count(*) FROM public.sys_user;
-- SELECT '当前角色数：' || count(*) FROM public.sys_role;
-- SELECT '当前应用数：' || count(*) FROM public.app;
-- SELECT '当前知识库数：' || count(*) FROM public.knowledge_base;
-- SELECT '当前文档数：' || count(*) FROM public.knowledge_file;
