-- =================================================================
-- PostgreSQL 数据库初始化脚本 (优化版)
-- 模块：用户与角色核心管理
-- 版本：2.0.2-Fixed
-- 说明：修复了主键缺失、Owner 硬编码、扩展依赖及幂等性问题，调整了UUID字段命名
-- =================================================================

-- 1. 开启事务，确保原子性
BEGIN;

-- 2. 设置环境参数
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

-- 3. 确保 UUID 扩展存在 (gen_random_uuid() 需要 pgcrypto)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =================================================================
-- 清理旧对象 (支持重复执行脚本)
-- 注意：生产环境请谨慎使用 DROP CASCADE，它会删除依赖此表的外键
-- =================================================================
DROP TABLE IF EXISTS public.sys_user_roles CASCADE;
DROP TABLE IF EXISTS public.sys_user CASCADE;
DROP TABLE IF EXISTS public.sys_role CASCADE;
DROP TABLE IF EXISTS public.app CASCADE;
DROP FUNCTION IF EXISTS public.update_updated_time() CASCADE;

-- =================================================================
-- 创建公共函数：自动更新 updated_time
-- =================================================================
CREATE OR REPLACE FUNCTION public.update_updated_time()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_time = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =================================================================
-- 1. 创建角色表 (sys_role)
-- =================================================================
CREATE TABLE public.sys_role (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(40) NOT NULL,
    code character varying(20),
    "order" integer NOT NULL DEFAULT 0,
    data_scope integer NOT NULL DEFAULT 1,
    uuid character varying(64) NOT NULL DEFAULT gen_random_uuid()::text,
    status character varying(10) NOT NULL DEFAULT '0',
    description text,
    created_time timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_time timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_sys_role PRIMARY KEY (id)
);

COMMENT ON TABLE public.sys_role IS '角色表';
COMMENT ON COLUMN public.sys_role.id IS '主键ID';
COMMENT ON COLUMN public.sys_role.name IS '角色名称';
COMMENT ON COLUMN public.sys_role.code IS '角色编码';
COMMENT ON COLUMN public.sys_role."order" IS '显示排序';
COMMENT ON COLUMN public.sys_role.data_scope IS '数据权限范围(1:仅本人 2:本部门 3:本部门及以下 4:全部 5:自定义)';
COMMENT ON COLUMN public.sys_role.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN public.sys_role.status IS '是否启用(0:启用 1:禁用)';
COMMENT ON COLUMN public.sys_role.description IS '备注/描述';
COMMENT ON COLUMN public.sys_role.created_time IS '创建时间';
COMMENT ON COLUMN public.sys_role.updated_time IS '更新时间';

-- =================================================================
-- 2. 创建用户表 (sys_user)
-- =================================================================
CREATE TABLE public.sys_user (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(32) NOT NULL,
    password character varying(255) NOT NULL,
    name character varying(32) NOT NULL,
    user_id character varying(64) NOT NULL DEFAULT gen_random_uuid()::text,
    mobile character varying(20), -- 放宽长度以支持国际号码
    email character varying(64),
    gender character varying(1) DEFAULT '2',
    avatar character varying(255),
    is_superuser boolean NOT NULL DEFAULT false,
    last_login timestamp with time zone,
    gitee_login character varying(32),
    github_login character varying(32),
    wx_login character varying(32),
    qq_login character varying(32),
    dept_id integer,
    status character varying(10) NOT NULL DEFAULT '0',
    description text,
    created_time timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_time timestamp without time zone NOT NULL DEFAULT NOW(),
    created_id integer,
    updated_id integer,
    CONSTRAINT pk_sys_user PRIMARY KEY (id),
    CONSTRAINT uk_sys_user_user_id UNIQUE (user_id)
);

COMMENT ON TABLE public.sys_user IS '用户表';
COMMENT ON COLUMN public.sys_user.id IS '主键ID';
COMMENT ON COLUMN public.sys_user.username IS '用户名/登录账号';
COMMENT ON COLUMN public.sys_user.password IS '密码哈希';
COMMENT ON COLUMN public.sys_user.name IS '昵称';
COMMENT ON COLUMN public.sys_user.user_id IS '用户UUID全局唯一标识';
COMMENT ON COLUMN public.sys_user.mobile IS '手机号';
COMMENT ON COLUMN public.sys_user.email IS '邮箱';
COMMENT ON COLUMN public.sys_user.gender IS '性别(0:男 1:女 2:未知)';
COMMENT ON COLUMN public.sys_user.avatar IS '头像URL地址';
COMMENT ON COLUMN public.sys_user.is_superuser IS '是否超管';
COMMENT ON COLUMN public.sys_user.last_login IS '最后一次登录时间';
COMMENT ON COLUMN public.sys_user.gitee_login IS 'Gitee登录';
COMMENT ON COLUMN public.sys_user.github_login IS 'Github登录';
COMMENT ON COLUMN public.sys_user.wx_login IS '微信登录';
COMMENT ON COLUMN public.sys_user.qq_login IS 'QQ登录';
COMMENT ON COLUMN public.sys_user.dept_id IS '部门ID';
COMMENT ON COLUMN public.sys_user.status IS '是否启用(0:启用 1:禁用)';
COMMENT ON COLUMN public.sys_user.description IS '备注/描述';
COMMENT ON COLUMN public.sys_user.created_time IS '创建时间';
COMMENT ON COLUMN public.sys_user.updated_time IS '更新时间';
COMMENT ON COLUMN public.sys_user.created_id IS '创建人ID';
COMMENT ON COLUMN public.sys_user.updated_id IS '更新人ID';

-- =================================================================
-- 3. 创建用户角色关联表 (sys_user_roles)
-- =================================================================
CREATE TABLE public.sys_user_roles (
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT pk_sys_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_sys_user_roles_user FOREIGN KEY (user_id) REFERENCES public.sys_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_sys_user_roles_role FOREIGN KEY (role_id) REFERENCES public.sys_role(id) ON DELETE CASCADE
);

COMMENT ON TABLE public.sys_user_roles IS '用户角色关联表';
COMMENT ON COLUMN public.sys_user_roles.user_id IS '用户ID';
COMMENT ON COLUMN public.sys_user_roles.role_id IS '角色ID';

-- =================================================================
-- 4. 创建索引
-- =================================================================
CREATE INDEX idx_sys_user_username ON public.sys_user USING btree (username);
CREATE INDEX idx_sys_user_mobile ON public.sys_user USING btree (mobile);
CREATE INDEX idx_sys_user_email ON public.sys_user USING btree (email);
CREATE INDEX idx_sys_user_status ON public.sys_user USING btree (status);
CREATE INDEX idx_sys_role_code ON public.sys_role USING btree (code);

-- =================================================================
-- 5. 创建触发器 (自动更新 updated_time)
-- =================================================================
CREATE TRIGGER update_sys_user_updated_time
BEFORE UPDATE ON public.sys_user
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_time();

CREATE TRIGGER update_sys_role_updated_time
BEFORE UPDATE ON public.sys_role
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_time();

-- =================================================================
-- 6. 插入初始数据
-- =================================================================

-- 6.1 插入默认超级管理员
-- 用户名: admin
-- 密码: admin123 (BCrypt 哈希: $argon2id$v=19$m=65536,t=3,p=4$vXchZ5IJb5m0iSsw+lB2MA$MzdSo0ikqcKMpubW6HMrmZgRjnPdBHd3ssVADb6tVoY)
INSERT INTO public.sys_user (
    username, password, name, is_superuser, status, description
) VALUES (
    'admin',
    '$argon2id$v=19$m=65536,t=3,p=4$vXchZ5IJb5m0iSsw+lB2MA$MzdSo0ikqcKMpubW6HMrmZgRjnPdBHd3ssVADb6tVoY',
    '超级管理员',
    true,
    '0',
    '系统内置最高权限账号'
);

-- 6.2 插入默认角色
INSERT INTO public.sys_role (
    name, code, "order", data_scope, status, description
) VALUES (
    '超级管理员',
    'admin',
    1,
    4,
    '0',
    '拥有系统所有权限及数据访问权'
);

-- 6.3 关联管理员与角色
-- 注意：由于使用了 IDENTITY 列，ID 从 1 开始自增，这里假设插入顺序保证 ID 为 1
INSERT INTO public.sys_user_roles (user_id, role_id)
VALUES (1, 1);

-- =================================================================
-- 创建 AI应用表 (app)
-- 用途：存储用户创建的AI应用/工作流基本信息和权限控制
-- 完整工作流配置存储在 MongoDB apps 集合中
-- =================================================================
CREATE TABLE public.app (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(200) NOT NULL,
    app_id character varying(64) NOT NULL DEFAULT gen_random_uuid()::text,
    user_id integer NOT NULL,
    description text,
    icon character varying(20) DEFAULT '🤖',
    is_public boolean NOT NULL DEFAULT false,
    type character varying(20) NOT NULL DEFAULT 'workflow',
    status character varying(10) NOT NULL DEFAULT '0',
    created_time timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_time timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_app PRIMARY KEY (id),
    CONSTRAINT uk_app_app_id UNIQUE (app_id)
);

COMMENT ON TABLE public.app IS 'AI应用表 - 存储应用基本信息和权限';
COMMENT ON COLUMN public.app.id IS '主键ID';
COMMENT ON COLUMN public.app.name IS '应用名称';
COMMENT ON COLUMN public.app.app_id IS '应用唯一标识，对应MongoDB App.app_id';
COMMENT ON COLUMN public.app.user_id IS '创建用户ID (权限控制)';
COMMENT ON COLUMN public.app.description IS '应用描述';
COMMENT ON COLUMN public.app.icon IS '应用图标emoji';
COMMENT ON COLUMN public.app.is_public IS '是否公开分享';
COMMENT ON COLUMN public.app.type IS '应用类型: workflow/ai/chat';
COMMENT ON COLUMN public.app.status IS '是否启用(0:启用 1:禁用)';
COMMENT ON COLUMN public.app.created_time IS '创建时间';
COMMENT ON COLUMN public.app.updated_time IS '更新时间';

-- 创建索引
CREATE INDEX idx_app_user_id ON public.app USING btree (user_id);
CREATE INDEX idx_app_status ON public.app USING btree (status);
CREATE INDEX idx_app_type ON public.app USING btree (type);
CREATE INDEX idx_app_is_public ON public.app USING btree (is_public);

-- 创建触发器 (自动更新 updated_time)
CREATE TRIGGER update_app_updated_time
BEFORE UPDATE ON public.app
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_time();

-- =================================================================
-- 插入默认应用
-- =================================================================
-- 默认工作流编排应用（系统内置）
INSERT INTO public.app (
    name, description, icon, is_public, type, user_id
) VALUES (
    '工作流编排',
    '可视化拖拽创建你的AI工作流，支持多节点条件分支',
    '⚙️',
    true,
    'workflow',
    1
);

-- =================================================================
-- 7. 提交事务
-- =================================================================
COMMIT;

-- 验证提示 (可选，执行完后可取消注释查看结果)
-- SELECT '初始化完成！当前用户数：' || count(*) FROM public.sys_user;
-- SELECT '当前角色数：' || count(*) FROM public.sys_role;
-- SELECT '当前应用数：' || count(*) FROM public.app;
