-- =================================================================
-- PostgreSQL 数据库初始化脚本 (优化版)
-- 模块：用户与角色核心管理
-- 版本：2.0.1-Fixed
-- 说明：修复了主键缺失、Owner 硬编码、扩展依赖及幂等性问题
-- =================================================================

-- 1. 开启事务，确保原子性
BEGIN;

-- 2. 设置环境参数
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

-- 3. 确保 UUID 扩展存在 (gen_random_uuid() 需要 pgcrypto)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =================================================================
-- 清理旧对象 (支持重复执行脚本)
-- 注意：生产环境请谨慎使用 DROP CASCADE，它会删除依赖此表的外键
-- =================================================================
DROP TABLE IF EXISTS public.sys_user_roles CASCADE;
DROP TABLE IF EXISTS public.sys_user CASCADE;
DROP TABLE IF EXISTS public.sys_role CASCADE;
DROP FUNCTION IF EXISTS public.update_updated_time() CASCADE;

-- =================================================================
-- 创建公共函数：自动更新 updated_time
-- =================================================================
CREATE OR REPLACE FUNCTION public.update_updated_time()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_time = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =================================================================
-- 1. 创建角色表 (sys_role)
-- =================================================================
CREATE TABLE public.sys_role (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(40) NOT NULL,
    code character varying(20),
    "order" integer NOT NULL DEFAULT 0,
    data_scope integer NOT NULL DEFAULT 1,
    uuid character varying(64) NOT NULL DEFAULT gen_random_uuid()::text,
    status character varying(10) NOT NULL DEFAULT '0',
    description text,
    created_time timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_time timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_sys_role PRIMARY KEY (id)
);

COMMENT ON TABLE public.sys_role IS '角色表';
COMMENT ON COLUMN public.sys_role.id IS '主键ID';
COMMENT ON COLUMN public.sys_role.name IS '角色名称';
COMMENT ON COLUMN public.sys_role.code IS '角色编码';
COMMENT ON COLUMN public.sys_role."order" IS '显示排序';
COMMENT ON COLUMN public.sys_role.data_scope IS '数据权限范围(1:仅本人 2:本部门 3:本部门及以下 4:全部 5:自定义)';
COMMENT ON COLUMN public.sys_role.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN public.sys_role.status IS '是否启用(0:启用 1:禁用)';
COMMENT ON COLUMN public.sys_role.description IS '备注/描述';
COMMENT ON COLUMN public.sys_role.created_time IS '创建时间';
COMMENT ON COLUMN public.sys_role.updated_time IS '更新时间';

-- =================================================================
-- 2. 创建用户表 (sys_user)
-- =================================================================
CREATE TABLE public.sys_user (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(32) NOT NULL,
    password character varying(255) NOT NULL,
    name character varying(32) NOT NULL,
    mobile character varying(20), -- 放宽长度以支持国际号码
    email character varying(64),
    gender character varying(1) DEFAULT '2',
    avatar character varying(255),
    is_superuser boolean NOT NULL DEFAULT false,
    last_login timestamp with time zone,
    gitee_login character varying(32),
    github_login character varying(32),
    wx_login character varying(32),
    qq_login character varying(32),
    dept_id integer,
    uuid character varying(64) NOT NULL DEFAULT gen_random_uuid()::text,
    status character varying(10) NOT NULL DEFAULT '0',
    description text,
    created_time timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_time timestamp without time zone NOT NULL DEFAULT NOW(),
    created_id integer,
    updated_id integer,
    CONSTRAINT pk_sys_user PRIMARY KEY (id)
);

COMMENT ON TABLE public.sys_user IS '用户表';
COMMENT ON COLUMN public.sys_user.id IS '主键ID';
COMMENT ON COLUMN public.sys_user.username IS '用户名/登录账号';
COMMENT ON COLUMN public.sys_user.password IS '密码哈希';
COMMENT ON COLUMN public.sys_user.name IS '昵称';
COMMENT ON COLUMN public.sys_user.mobile IS '手机号';
COMMENT ON COLUMN public.sys_user.email IS '邮箱';
COMMENT ON COLUMN public.sys_user.gender IS '性别(0:男 1:女 2:未知)';
COMMENT ON COLUMN public.sys_user.avatar IS '头像URL地址';
COMMENT ON COLUMN public.sys_user.is_superuser IS '是否超管';
COMMENT ON COLUMN public.sys_user.last_login IS '最后登录时间';
COMMENT ON COLUMN public.sys_user.gitee_login IS 'Gitee登录';
COMMENT ON COLUMN public.sys_user.github_login IS 'Github登录';
COMMENT ON COLUMN public.sys_user.wx_login IS '微信登录';
COMMENT ON COLUMN public.sys_user.qq_login IS 'QQ登录';
COMMENT ON COLUMN public.sys_user.dept_id IS '部门ID';
COMMENT ON COLUMN public.sys_user.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN public.sys_user.status IS '是否启用(0:启用 1:禁用)';
COMMENT ON COLUMN public.sys_user.description IS '备注/描述';
COMMENT ON COLUMN public.sys_user.created_time IS '创建时间';
COMMENT ON COLUMN public.sys_user.updated_time IS '更新时间';
COMMENT ON COLUMN public.sys_user.created_id IS '创建人ID';
COMMENT ON COLUMN public.sys_user.updated_id IS '更新人ID';

-- =================================================================
-- 3. 创建用户角色关联表 (sys_user_roles)
-- =================================================================
CREATE TABLE public.sys_user_roles (
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT pk_sys_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_sys_user_roles_user FOREIGN KEY (user_id) REFERENCES public.sys_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_sys_user_roles_role FOREIGN KEY (role_id) REFERENCES public.sys_role(id) ON DELETE CASCADE
);

COMMENT ON TABLE public.sys_user_roles IS '用户角色关联表';
COMMENT ON COLUMN public.sys_user_roles.user_id IS '用户ID';
COMMENT ON COLUMN public.sys_user_roles.role_id IS '角色ID';

-- =================================================================
-- 4. 创建索引
-- =================================================================
CREATE INDEX idx_sys_user_username ON public.sys_user USING btree (username);
CREATE INDEX idx_sys_user_mobile ON public.sys_user USING btree (mobile);
CREATE INDEX idx_sys_user_email ON public.sys_user USING btree (email);
CREATE INDEX idx_sys_user_status ON public.sys_user USING btree (status);
CREATE INDEX idx_sys_role_code ON public.sys_role USING btree (code);

-- =================================================================
-- 5. 创建触发器 (自动更新 updated_time)
-- =================================================================
CREATE TRIGGER update_sys_user_updated_time
BEFORE UPDATE ON public.sys_user
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_time();

CREATE TRIGGER update_sys_role_updated_time
BEFORE UPDATE ON public.sys_role
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_time();

-- =================================================================
-- 6. 插入初始数据
-- =================================================================

-- 6.1 插入默认超级管理员
-- 用户名: admin
-- 密码: admin123 (BCrypt 哈希: $2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW)
INSERT INTO public.sys_user (
    username, password, name, is_superuser, status, description
) VALUES (
    'admin',
    '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW',
    '超级管理员',
    true,
    '0',
    '系统内置最高权限账号'
);

-- 6.2 插入默认角色
INSERT INTO public.sys_role (
    name, code, "order", data_scope, status, description
) VALUES (
    '超级管理员',
    'admin',
    1,
    4,
    '0',
    '拥有系统所有权限及数据访问权'
);

-- 6.3 关联管理员与角色
-- 注意：由于使用了 IDENTITY 列，ID 从 1 开始自增，这里假设插入顺序保证 ID 为 1
INSERT INTO public.sys_user_roles (user_id, role_id)
VALUES (1, 1);

-- =================================================================
-- 7. 提交事务
-- =================================================================
COMMIT;

-- 验证提示 (可选，执行完后可取消注释查看结果)
-- SELECT '初始化完成！当前用户数：' || count(*) FROM public.sys_user;
-- SELECT '当前角色数：' || count(*) FROM public.sys_role;